"""empty message

Revision ID: 15dbb008eccc
Revises: e7d126d4ae81
Create Date: 2020-11-14 17:12:00.606645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dbb008eccc'
down_revision = 'e7d126d4ae81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('orders', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Orders_invoice'), 'Orders', ['invoice'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Orders_invoice'), table_name='Orders')
    op.drop_table('Orders')
    # ### end Alembic commands ###
